blog/urls.py
from django.urls import path
from .views import PostView, PostDetailedView, AddPostView, user_login, authenticate_user, register, logout_view

app_name = 'blog'
urlpatterns = [
    path('', PostView.as_view(), name="blog"),
    path('login/', user_login, name="login"),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),
    path('authenticate_user/', authenticate_user, name='authenticate_user'),
    path('article/<int:pk>', PostDetailedView.as_view(), name="article-detail"),
    path('add_post/', AddPostView.as_view(), name='add_post')
]

mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('theWebsite.urls')),
    path('blog/', include('blog.urls')),
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theWebsite/urls.py
from django.urls import path
from .views import index, testimonies

app_name = 'theWebsite'

urlpatterns = [
    path('', index, name='index'),
    path('testimonies/', testimonies, name='testimonies')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    CATEGORY_CHOICES = [
        ('Testimony', 'Testimony'),
        ('Encouragement', 'Encouragement'),
        ('General', 'General'),
    ]
    
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=15, choices=CATEGORY_CHOICES)
    content = models.TextField()
    image = models.ImageField(upload_to='post_images', blank=True)

    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse('blog:article-detail', args=(str(self.id),) )

theWebsite/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView, DetailView
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.forms import ModelForm
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django import forms


def user_login(request):
    """
    Displays the login page.
    """
    return render(request, 'login.html')


def authenticate_user(request):
    """
    Authenticates the user and redirects to the appropriate page based on the authentication result.
    """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)

    if user is None:
        return HttpResponseRedirect(reverse('blog:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('blog:add_post'))


def register(request):
    """
    Handles the user registration process.
    """
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blog:login')
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})


def logout_view(request):
    """
    Logs out the user and redirects to the index page.
    """
    logout(request)
    return redirect('theWebsite:index')


class PostView(ListView):
    """
    Displays a list of posts.
    """
    model = Post
    template_name = 'blog.html'


class PostDetailedView(DetailView):
    """
    Displays the details of a specific post.
    """
    model = Post
    template_name = 'post_details.html'


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class AddPostView(LoginRequiredMixin, View):
    """
    Handles the creation of new posts.
    """
    login_url = 'blog:login'
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'

    def get(self, request):
        """
        Displays the form for adding a new post.
        """
        form = PostForm(initial={'author': request.user})  # Set the initial value of the author field
        return render(request, 'add_post.html', {'form': form})

    def post(self, request):
        """
        Handles the submission of the form for adding a new post.
        """
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:blog')  # Redirect to the list of posts

        return render(request, 'add_post.html', {'form': form})

    def get_form(self, form_class=None):
        """
        Returns the form instance with the author field hidden.
        """
        form = super().get_form(form_class)
        form.fields['author'].widget = forms.HiddenInput()  # Hide the author field
        return form

    def form_valid(self, form):
        """
        Sets the logged-in user as the author of the post.
        """
        form.instance.author = self.request.user
        return super().form_valid(form)

theWebsite/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')


def testimonies(request):
    return render(request, 'testimonies.html')

blog/templates/add_post.html
{% extends 'base.html' %}

{% block title %}Testify, Share, Encourage{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/add_post.css' %}">
{% endblock %}

{% block content %}

<div class="main-section">
    <h1>Share your story with others</h1>

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
        <div class="form-group">
        <label for="{{ form.title.id_for_label }}">Title</label>
        {{ form.title }}
        </div>
    
        <div class="form-group">
        <label for="{{ form.author.id_for_label }}">Author</label>
        {{ form.author }}
        </div>
    
        <div class="form-group">
        <label for="{{ form.category.id_for_label }}">Category</label>
        {{ form.category }}
        </div>
    
        <div class="form-group">
        <label for="{{ form.content.id_for_label }}">Content</label>
        {{ form.content }}
        </div>
    
        <div class="form-group">
        <label for="{{ form.image.id_for_label }}">Image</label>
        {{ form.image }}
        </div>
    
        <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>


  
{% endblock %}

blog/templates/blog.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block content %}

<h1></h1>

    <div class="blog-container">
        <div class="row">
          {% for post in object_list %}
          <div class="col-md-4">
            <div class="blog-post">

                {% if post.image and post.image.url %}
                    <img src="{{ post.image.url }}" alt="Blog Image" class="blog-image">
                {% endif %}

                <a href="{% url 'blog:article-detail' post.pk %}">
                    <h2>{{ post.title }}</h2>
                    <p>{{ post.category }}</p>
                </a> 
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      

{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/login.css' %}">
{% endblock %}

{% block content %}

<div class="main-section">

    <h1>Uplift other believers </h1>

    <h2>Testify • Encourage • Fellowship</h2>

    <form action="{% url 'blog:authenticate_user' %}" method="post">
        
        {% csrf_token %}

        <label>Username</label>
        <input type="text" name="username" placeholder="User" required>

        <br/><br/>

        <label>Password</label>
        <input type="password" name="password" required>

        <br/><br/>

        <input type="submit" value="Login" />
    </form>

</div>

{% endblock %}

blog/templates/post_details.html
{% extends 'base.html' %}

{% block title %} {{ post.author.title }} {% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/post_details.css' %}">
{% endblock %}

{% block content %}
    <div class="post-details">

        <div class="author-section">
            {% if post.image and post.image.url %}
            <img src="{{ post.image.url }}" alt="Blog Image" class="blog-image author-image">
            {% endif %}
            <h1 class="author-title">{{ post.author.title }}</h1>
            <small class="author-info">By: {{ post.author.first_name }} - {{ post.category }}</small>
        </div>
                
        <div class="content-section">
            {{ post.content }}
        </div>
        
        <a href="{% url 'blog:blog' %}" class="back-link">Back</a>
    </div> 

{% endblock %}

blog/templates/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/register.css' %}">
{% endblock %}
 
{% block content %}

<div class="container main-section" style="margin-top: 50px;">
  <div class="row">
    <div class="col-md-4 d-flex align-items-center justify-content-center">
      <h1 class="text-center">Be part of God's global family</h1>
    </div>
    <div class="col-md-8">
      <form method="post" style="margin-top: 50px;">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Register</button>
      </form>
    </div>
  </div>
</div>



{% endblock %}

theWebsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'theWebsite/css/styles.css' %}">
    {% block styles %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'theWebsite:index' %}">The Lord Jesus Christ</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-auto">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'theWebsite:testimonies' %}">Testimonies</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href=" {% url 'blog:blog' %}">Blog</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href=" {% url 'blog:add_post' %}">Share a testimony</a>
              </li>

            </ul>

            <ul class="navbar-nav mb-2 mb-lg-0 me-auto">

              <li class="nav-item ml-auto">

                {% if user.is_authenticated %}
                  <a href="{% url 'blog:logout' %}" class="nav-link">Logout</a>
                {% else %}
                  <a href="{% url 'blog:login' %}" class="nav-link">Login</a>
                {% endif %}

              </li>

              <li class="nav-item ml-auto">
                <a class="nav-link" href="{% url 'blog:register' %}">Register</a>
              </li>
            </ul>

          </div>
        </div>
    </nav>
      



    {% block content %}
    
    {% endblock %}

    <footer class="py-3">
        <div class="container">
          <div class="d-flex justify-content-between align-items-center">
            <a class="text-primary" href="https://www.biblegateway.com/passage/?search=John%203%3A16&version=KJV" target="_blank">
              <p class="footer-p">God Loves you</p>
            </a>
            <p class="footer-p"> <a class="text-decoration-none text-primary" href="tel:+27837182700">083 718 2700</a> </p>
            <p class="footer-p">JESUS IS KING</p>
          </div>
        </div>
    </footer>
      

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">

    </script>

</body>
</html>

theWebsite/templates/index.html
{% extends 'base.html' %}

{% block title %}Who's Jesus?{% endblock %}

{% block content %}
    <!-- Homepage content goes here -->

    <section class="hero d-flex align-items-center justify-content-center">
        <div class="container text-left">
          <h1 style="padding-bottom: 25px; color: #000;">Do you want to know more about Jesus Christ?</h1>
          <h3 style="padding-bottom: 25px; color: #000;">You have come to the right place</h3>
          <a href="#section2" class="btn btn-primary mt-3">Learn more</a>
        </div>
      </section>      

    <section id="section2" class="mt-5" style="padding-top: 200px; padding-bottom: 200px;">
        <div class="container text-center">
            <h2>
            2000 years ago an ordinary woman was visited by an <a href="https://www.biblegateway.com/passage/?search=Luke%201%3A26-38&version=ESV" target="_blank"> Angel </a> and she was told she was going to conceive by the Holy Spirit
            </h2>

            <h5 style="padding-top: 25px;">
              <p>
                From that was born a man known to many today as the light of the world 
                <a href="https://www.biblegateway.com/passage/?search=John%208%3A12&version=ESV" target="_blank"> John 8:12</a>
              </p>
            </h5>
        
        </div>
    </section>


    <section class="testimony-section" id="testimony-section" style="background-color: #b29267; color: #fff">
        <div class="container py-5">
          <h2 class="mb-4" style="padding-bottom: 35px;">
            The light of the world was not only a light that shone 2000 years ago but still shines in many people's lives today <a href="{% url 'theWebsite:testimonies' %}">see testimonies</a>
          </h2>
          
          <div class="row">

            <div class="col-md-4">
              <h4>Jesus brings transformation</h4>
              <p>
                <iframe width="360" height="315" src="https://www.youtube.com/embed/IJyUhRvGZPk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
              </p>
            </div>

            <div class="col-md-4">
              <h4>God our rescuer</h4>
              <p>
                <iframe width="360" height="315" src="https://www.youtube.com/embed/OaNtiL01Xh0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
              </p>
            </div>

            <div class="col-md-4">
              <h4>Finding the TRUTH in Jesus</h4>
              <p>
                <iframe width="360" height="315" src="https://www.youtube.com/embed/1Dd2uRJRThU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
              </p>
            </div>

          </div>


        </div>
      </section>
      

    <section class="bg-light">

        <div class="container py-5">
            <div class="row">
                <div class="col-md-8 mx-auto text-center">
                    <h1 class="mb-4">
                      If you have been touched by testimonies you have watched and wish to make Jesus the Lord of your life pray this prayer:
                    </h1>
                    <h4 class="mb-4">
                        Lord Jesus, I confess my sins and ask for your forgiveness. Please come into my heart as my Lord and Savior. Take complete control of my life and help me to walk in Your footsteps daily by the power of the Holy Spirit. Thank you Lord for saving me and for answering my prayer.
                    </h4>
                    <h5 class="mb-4">
                        Congratulations, Your life will never be the same! Here's what's next: <a href="https://content.cfan.org/recklesslove/booklet/ntyas.pdf" target="_blank">Now that you are saved</a>
                    </h5>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

theWebsite/templates/testimonies.html
{% extends 'base.html' %}

{% block title %}Testimonies{% endblock %}

{% block styles %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'theWebsite/css/testimony.css' %}">

{% endblock %}

{% block content %}

<div class="test-container">
    <div class="row">

      <div class="col">
        <h1 class="text-center">Be blessed</h1>
        <p class="text-center">Feel free to contact us to share your story with others to bless them</p>
      </div>

      <div class="col">

        <div class="row">
          <div class="col">
            <p>
                <iframe width="80%" height="150%" src="https://www.youtube.com/embed/9NSKqC8h28U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p>
                <iframe width="80%" height="150%" src="https://www.youtube.com/embed/KDq-878ffW0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </p>
          </div>
        </div>
      </div>
    </div>
</div>
  
  

{% endblock %}